theme: minima
markdown: kramdown

title: Speeding Up Optimization-based Motion Planning through Deep Learning

author: johannes.tenhumberg@dlr.de

header_pages:
  - _pages/robots.md
  - _pages/worlds.md
  - _pages/chomp.md
  - _pages/bps.md
  - _pages/methods.md
  - _pages/training.md
  - _pages/results.md
  - _pages/dataset.md
  - _pages/gallery.md
  - _pages/code.md

include:
    - _pages

exclude:
    - .gitignore
    - Gemfile
    - README.md


